name: Flutter build and test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  flutter_get:
    name: Run flutter get and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'statble'

      - run: flutter pub get
      - run: flutter analyze

  build_android:
    name: build flutter (android)
    needs: [flutter_get]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'statble'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - run: flutter build appbundle


      