name: Flutter build and test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  flutter_build_android:
    name: Run flutter get and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.5'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk -t lib/app/main.dart
      - run: flutter build appbundle -t lib/app/main.dart


      
