name: Flutter build and test

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  flutter_build_android:
    name: Run flutter get and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK Temurin-17.0.5
        uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - name: Set up Flutter version 3.7.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk -t lib/app/main.dart
      - run: flutter build appbundle -t lib/app/main.dart


      